
# Part B: Dataset Understanding & Preparation

## Objectives
1. Identify features and target variable
2. Perform train-test split
3. Apply basic preprocessing (scaling where required)

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv('Advanced Regression HousePrice.csv')

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (3800, 12)

,property_id,sale_date,area_sqft,bedrooms,bathrooms,location_score,property_age,distance_city_km,near_school,near_metro,crime_rate_index,house_price_inr
0,200001,2014-01-01,2181,6,4,8.1,21,3.8,0,0,4.84,35154898
1,200002,2019-12-01,2383,5,4,5.3,28,10.9,1,1,2.89,26710893
2,200003,2016-10-01,1047,3,3,5.9,7,27.5,0,1,4.04,11216242
3,200004,2013-03-01,1753,4,3,7.0,27,12.1,0,0,3.28,21984310
4,200005,2013-07-01,1728,4,4,10.0,32,1.4,0,1,3.84,25080429

## Dataset Overview

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3800 entries, 0 to 3799
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   property_id       3800 non-null   int64
 1   sale_date         3800 non-null   object
 2   area_sqft         3800 non-null   int64
 3   bedrooms          3800 non-null   int64
 4   bathrooms         3800 non-null   int64
 5   location_score    3800 non-null   float64
 6   property_age      3800 non-null   int64
 7   distance_city_km  3800 non-null   float64
 8   near_school       3800 non-null   int64
 9   near_metro        3800 non-null   int64
 10  crime_rate_index  3800 non-null   float64
 11  house_price_inr   3800 non-null   int64
dtypes: float64(3), int64(8), object(1)
memory usage: 356.4+ KB

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
property_id,3800.0,2.019005e+05,1.097110e+03,200001.0,200950.75,201900.50,202850.25,203800.0
area_sqft,3800.0,1.716926e+03,5.829966e+02,500.0,1322.00,1700.50,2105.00,3776.0
bedrooms,3800.0,3.428158e+00,1.356682e+00,1.0,2.00,3.00,4.00,7.0
bathrooms,3800.0,2.916316e+00,1.133540e+00,1.0,2.00,3.00,4.00,6.0
location_score,3800.0,6.502237e+00,1.766945e+00,1.0,5.30,6.50,7.70,10.0
property_age,3800.0,2.253711e+01,1.232574e+01,1.0,14.00,20.00,29.00,80.0
distance_city_km,3800.0,1.308513e+01,6.537425e+00,1.0,8.50,13.00,17.50,38.7
near_school,3800.0,5.484211e-01,4.977154e-01,0.0,0.00,1.00,1.00,1.0
near_metro,3800.0,4.728947e-01,4.993305e-01,0.0,0.00,0.00,1.00,1.0
crime_rate_index,3800.0,4.242911e+00,2.045371e+00,0.5,2.81,4.22,5.65,12.0
house_price_inr,3800.0,2.071940e+07,8.707465e+06,1506126.0,14468946.50,19891801.50,25960617.50,59303146.0


## Task 1: Identify Features and Target Variable
Target Variable:
- house_price_inr

Features:
- area_sqft
- bedrooms
- bathrooms
- location_score
- property_age
- distance_city_km
- near_school
- near_metro
- crime_rate_index

In [5]:
# Convert date column to datetime
df['sale_date'] = pd.to_datetime(df['sale_date'])

# Extract useful time features
df['sale_year'] = df['sale_date'].dt.year
df['sale_month'] = df['sale_date'].dt.month

# Feature Matrix
X = df.drop(columns=['house_price_inr', 'sale_date'])

# Target Variable
y = df['house_price_inr']

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

X.head()

Feature Shape: (3800, 12)
Target Shape: (3800,)

,property_id,area_sqft,bedrooms,bathrooms,location_score,property_age,distance_city_km,near_school,near_metro,crime_rate_index,sale_year,sale_month
0,200001,2181,6,4,8.1,21,3.8,0,0,4.84,2014,1
1,200002,2383,5,4,5.3,28,10.9,1,1,2.89,2019,12
2,200003,1047,3,3,5.9,7,27.5,0,1,4.04,2016,10
3,200004,1753,4,3,7.0,27,12.1,0,0,3.28,2013,3
4,200005,1728,4,4,10.0,32,1.4,0,1,3.84,2013,7

## Task 2: Train-Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Target   :", y_train.shape)
print("Testing Target    :", y_test.shape)

Training Features : (3040, 12)
Testing Features  : (760, 12)
Training Target   : (3040,)
Testing Target    : (760,)


## Taskk 3: Feature Scaling

Scaling is applied because:
- Ridge Regression
- Lasso Regression
- Support Vector Regression

perform better when features are on a similar scale.

In [7]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled Training Shape:", X_train_scaled.shape)
print("Scaled Testing Shape :", X_test_scaled.shape)

Scaled Training Shape: (3040, 12)
Scaled Testing Shape : (760, 12)

In [12]:
X_test_scaled

array([[-0.83290509, -0.64893666, -1.05843013, ...,  2.42803917,
        -1.10493187,  0.7335169 ],
       [-1.20828955,  1.03865662,  1.88879002, ..., -0.49536855,
         1.38026559, -0.13448286],
       [-1.33035833,  0.45159324,  0.41517994, ...,  0.0162278 ,
         1.38026559, -1.00248261],
       ...,
       [ 0.08582312,  1.0506375 , -0.32162509, ...,  1.02480346,
         0.63470635,  0.44418365],
       [ 1.02015411, -0.23131723,  0.41517994, ...,  0.72759035,
        -0.35937263, -1.58114912],
       [ 1.37718236,  1.38781385,  1.15198498, ..., -0.21764482,
        -1.10493187,  1.02285015]], shape=(760, 12))

In [9]:
scaled_df = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)

scaled_df.head()

,property_id,area_sqft,bedrooms,bathrooms,location_score,property_age,distance_city_km,near_school,near_metro,crime_rate_index,sale_year,sale_month
0,-1.527688,1.285121,1.888790,2.705537,-0.350289,0.442044,-0.289519,-1.101144,1.055484,1.512038,1.131746,1.312183
1,-0.962316,-1.376348,-1.795235,-1.687601,1.086406,0.279914,-0.961041,0.908146,1.055484,0.103930,-0.856412,1.601517
2,-1.079796,-0.036200,0.415180,-0.808973,0.626663,-0.936061,-1.846229,-1.101144,-0.947432,0.201377,-0.110853,1.601517
3,-1.289975,0.119552,-1.058430,-0.808973,1.316277,-0.936061,-1.327326,0.908146,-0.947432,0.157526,0.883226,0.733517
4,-0.241835,-0.992959,-1.058430,0.069654,0.741599,-1.017126,0.885645,-1.101144,1.055484,0.927357,-0.359373,0.154850


## Missing Values Check

In [10]:
df.isnull().sum()

property_id         0
sale_date           0
area_sqft           0
bedrooms            0
bathrooms           0
location_score      0
property_age        0
distance_city_km    0
near_school         0
near_metro          0
crime_rate_index    0
house_price_inr     0
sale_year           0
sale_month          0
dtype: int64


## Final Summary

### Target Variable
- house_price_inr

### Features Used
- property_id
- area_sqft
- bedrooms
- bathrooms
- location_score
- property_age
- distance_city_km
- near_school
- near_metro
- crime_rate_index
- sale_year
- sale_month

### Train-Test Split
- 80% Training Data
- 20% Testing Data

### Preprocessing Applied
- Datetime feature extraction
- Standard Scaling
- Missing value inspection